apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "nginx.fullname" . }}-config
data:
  nginx.conf: |
{{ .Files.Get "config/nginx.conf" | indent 4 }}
  extra.conf: |
{{ .Files.Get "config/extra.conf" | indent 4 }}
