{{- if and .Values.envConfig.enabled (not .Values.envConfig.existingName) }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "generic.envConfigName" . }}
  labels:
    {{- include "generic.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.envConfig.data }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
{{- if and .Values.fileConfig.enabled (not .Values.fileConfig.existingName) }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "generic.fileConfigName" . }}
  labels:
    {{- include "generic.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.fileConfig.data }}
  {{ $key }}: |-
    {{- $value | nindent 4 }}
  {{- end }}
{{- end }}
