{{- if and .Values.envSecret.enabled (not .Values.envSecret.existingName) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "generic.envSecretName" . }}
  labels:
    {{- include "generic.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.envSecret.stringData }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
{{- if and .Values.fileSecret.enabled (not .Values.fileSecret.existingName) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "generic.fileSecretName" . }}
  labels:
    {{- include "generic.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.fileSecret.stringData }}
  {{ $key }}: |-
    {{- $value | nindent 4 }}
  {{- end }}
{{- end }}
