apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: demo-app-config-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: default
    kind: ClusterSecretStore
  target:
    name: demo-app-config-secret
    creationPolicy: Owner
  data:
    - secretKey: POSTGRES_HOST
      remoteRef:
        key: /demo-app/database
        property: host
    - secretKey: POSTGRES_USER
      remoteRef:
        key: /demo-app/database
        property: username
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: /demo-app/database
        property: password
